# Generated by Django 2.1.2 on 2018-12-21 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='host',
            table='host',
        ),
    ]
